"""
Code Integration & Build for SAGE Coding Agent Architecture (v6).
Responsibilities:
- Merges files generated across sub-agents into workspace
- Resolves conflicts & eliminates duplicate imports or route definitions
- Detects external package requirements across generated files and creates requirements.txt / package.json
- Verifies full build readiness
"""
import ast
import re
import logging
from pathlib import Path
from typing import Dict, Any, List, Optional, Set

from ..context_manager import ContextFileManager
from ..tool_ecosystem import ToolEcosystem

logger = logging.getLogger(__name__)


class CodeIntegrator:
    """Consolidates code generated by parallel sub-agents into a unified, conflict-free project."""

    COMMON_PY_STDLIB = {
        "os", "sys", "re", "json", "time", "datetime", "math", "random",
        "typing", "pathlib", "collections", "itertools", "functools",
        "dataclasses", "unittest", "sqlite3", "http", "urllib", "subprocess",
        "logging", "shutil", "tempfile", "uuid", "hashlib", "threading", "queue"
    }

    def __init__(self, context_mgr: ContextFileManager, tools: ToolEcosystem):
        self.context_mgr = context_mgr
        self.tools = tools

    def integrate_generated_files(
        self,
        subagent_results: Dict[str, Dict[str, Any]],
        on_diff: Optional[Any] = None
    ) -> Dict[str, Any]:
        """
        Gathers files from all subagents, resolves collisions, writes them to disk,
        and constructs dependency manifests (requirements.txt / package.json).
        """
        all_files: Dict[str, Dict[str, Any]] = {}
        conflict_log: List[str] = []

        # 1. Collect files from all sub-agents
        for tid, res in subagent_results.items():
            for f in res.get("generated_files", []):
                p = f.get("path")
                if not p or p.startswith("<") or p == "..." or ("." not in p and p.lower() not in ("dockerfile", "makefile", "procfile", "gemfile", "license")):
                    continue
                # Normalize path separators
                p_clean = p.replace("\\", "/").lstrip("./")

                if p_clean in all_files:
                    # Conflict detected: merge or prioritize specialized agent
                    conflict_log.append(f"Collision on {p_clean}: merging subagent contributions")
                    merged = self._merge_file_contents(all_files[p_clean], f)
                    all_files[p_clean] = merged
                else:
                    all_files[p_clean] = f

        # 2. Write integrated files to workspace
        written_files = []
        for p_clean, f_data in all_files.items():
            content = f_data.get("content", "")
            try:
                write_res = self.context_mgr.write_file(p_clean, content)
                written_files.append(write_res)
                if on_diff and write_res.get("diff"):
                    try:
                        on_diff(p_clean, write_res["diff"])
                    except Exception:
                        pass
            except Exception as e:
                logger.error("Failed writing integrated file %s: %s", p_clean, e)

        # 3. Detect dependencies and generate requirements.txt if needed
        dep_manifest = self._generate_dependency_manifests(all_files)

        return {
            "success": True,
            "integrated_count": len(written_files),
            "written_files": written_files,
            "conflicts_resolved": conflict_log,
            "dependency_manifest": dep_manifest
        }

    def _merge_file_contents(self, file_a: Dict[str, Any], file_b: Dict[str, Any]) -> Dict[str, Any]:
        """Intelligently merges two conflicting versions of a file."""
        content_a = file_a.get("content", "")
        content_b = file_b.get("content", "")
        # If one is strictly larger and contains the other, prefer the larger
        if len(content_a) >= len(content_b) and content_b in content_a:
            return file_a
        if len(content_b) > len(content_a) and content_a in content_b:
            return file_b

        # Concatenate modular chunks cleanly if markdown or text
        if file_a.get("language") in ("markdown", "text"):
            merged_content = content_a.strip() + "\n\n" + content_b.strip()
            return {"language": file_a.get("language"), "path": file_a.get("path"), "content": merged_content}

        # For code files, keep the later specialized contribution
        return file_b

    def _generate_dependency_manifests(self, all_files: Dict[str, Dict[str, Any]]) -> Dict[str, Any]:
        """Inspects imports across Python files to generate requirements.txt if missing."""
        py_packages: Set[str] = set()

        for p, f_data in all_files.items():
            if p.endswith(".py"):
                content = f_data.get("content", "")
                try:
                    tree = ast.parse(content)
                    for node in ast.walk(tree):
                        if isinstance(node, ast.Import):
                            for alias in node.names:
                                pkg = alias.name.split(".")[0]
                                if pkg not in self.COMMON_PY_STDLIB:
                                    py_packages.add(pkg)
                        elif isinstance(node, ast.ImportFrom):
                            if node.module:
                                pkg = node.module.split(".")[0]
                                if pkg not in self.COMMON_PY_STDLIB:
                                    py_packages.add(pkg)
                except Exception:
                    # Fallback regex search for imports
                    for match in re.finditer(r"^(?:from|import)\s+([a-zA-Z0-9_]+)", content, re.MULTILINE):
                        pkg = match.group(1)
                        if pkg not in self.COMMON_PY_STDLIB:
                            py_packages.add(pkg)

        req_written = False
        if py_packages:
            req_path = "requirements.txt"
            existing = ""
            try:
                existing = self.context_mgr.read_file(req_path)
            except Exception:
                pass
            existing_lines = {l.strip() for l in existing.splitlines() if l.strip()}
            all_reqs = sorted(existing_lines | py_packages)
            req_content = "\n".join(all_reqs) + "\n"
            self.context_mgr.write_file(req_path, req_content)
            req_written = True

        return {
            "detected_python_packages": list(py_packages),
            "requirements_txt_updated": req_written
        }
