"""
Response Validator for Sage AI Auto Router.
Performs semantic format verification, AST code syntax validation, and quality checks.
"""
import ast
import re
import logging
from typing import Tuple, Optional, Any, Union
from engine.providers.base_provider import ProviderResponse
from .models import TaskType

logger = logging.getLogger(__name__)


class ResponseValidator:
    """Validates model responses for syntax correctness, completion quality, and safety."""

    @classmethod
    def validate(
        cls,
        resp: Any,
        task: TaskType = TaskType.GENERAL_CHAT
    ) -> Tuple[bool, Optional[str]]:
        """
        Validates response output.
        Returns (True, None) if passed, or (False, failure_reason) if rejected.
        """
        if isinstance(resp, str):
            text = resp.strip()
            if not text:
                return False, "Empty response."
            resp = ProviderResponse(text=text, model_name="Validator", provider_id="validator", success=True)

        if not resp.success:
            return False, resp.error_msg or "Provider reported execution failure."

        text = (resp.text or "").strip()
        if not text:
            return False, "Empty output generated by model."

        # Reject common refusal or API error leakages
        refusal_patterns = [
            r"^\{[\s\S]*\"error\":[\s\S]*\}$",
            r"^Error:\s*(401|403|404|429|500|502|503)",
            r"^\b(I apologize, but as an AI I am unable to connect|Rate limit exceeded|Quota exceeded)\b"
        ]
        for pat in refusal_patterns:
            if re.search(pat, text, re.IGNORECASE):
                return False, f"Model output detected as error/refusal payload: {text[:80]}"

        # Specialized Coding Task Validation
        if task == TaskType.CODING:
            code_blocks = re.findall(r"```(?:python|py)?\s*([\s\S]*?)```", text)
            if code_blocks:
                for block in code_blocks:
                    block_stripped = block.strip()
                    if not block_stripped:
                        continue
                    # Check Python AST syntax if block looks like Python
                    if any(k in block_stripped for k in ("def ", "import ", "class ", "print(", "for ", "if __name__")):
                        try:
                            ast.parse(block_stripped)
                        except SyntaxError as syn_err:
                            logger.info("AST syntax validation error in generated code: %s", syn_err)
                            return False, f"Python AST syntax validation failed on line {syn_err.lineno}: {syn_err.msg}"
            elif len(text) < 15:
                return False, "Coding response too short or missing implementation code."

        # Specialized Image Task Validation
        if task == TaskType.IMAGE_GEN:
            if not resp.is_image and not resp.image_data and not any(k in text.lower() for k in ("data:image", "http://", "https://", "png", "jpg")):
                return False, "Image generator did not produce valid image payload."

        return True, None
