"""
Documentation Agent for SAGE Coding Agent Architecture (v6).
Responsibilities:
- Comprehensive README.md generation
- API documentation (OpenAPI / Swagger specifications)
- Setup and quickstart guides
- Architecture summary and deployment walkthroughs
- Inline code docstring audits
"""
import logging
from typing import Dict, Any, List, Optional, Callable

from .base_sub_agent import BaseSubAgent

logger = logging.getLogger(__name__)


class DocumentationAgent(BaseSubAgent):
    """Specialized in developer documentation, READMEs, API specifications, and setup guides."""

    def __init__(self, context_mgr, tools, model_router=None):
        super().__init__(role="documentation", name="Documentation Agent", context_mgr=context_mgr, tools=tools, model_router=model_router)

    def execute(
        self,
        task: Dict[str, Any],
        dep_context: Dict[str, Any],
        llm_caller_fn: Optional[Callable[..., Dict[str, Any]]] = None
    ) -> Dict[str, Any]:
        instruction = task.get("instruction", "")

        # Summary of generated files across all previous agents
        manifest_summary = []
        for dep_res in dep_context.values():
            for gf in dep_res.get("generated_files", []):
                manifest_summary.append(f"- `{gf.get('path')}` ({gf.get('language')})")

        system_prompt = (
            "You are Sage AI's Principal Technical Writer. "
            "Write production-grade documentation including comprehensive README.md, API specs, and setup instructions. "
            "Specify documentation files in markdown code fences, e.g.:\n"
            "```markdown file:README.md\n# Project Title\n```\n"
            "```markdown file:docs/api_reference.md\n# API Reference\n```"
        )

        prompt = (
            f"Documentation Task: {instruction}\n\n"
            f"Project Files Manifest:\n{chr(10).join(manifest_summary) if manifest_summary else 'Full-stack application.'}\n\n"
            "Generate complete, beautiful documentation files with installation, usage, API endpoints, and architecture guide."
        )

        llm_res = self.call_llm(prompt=prompt, system_prompt=system_prompt, llm_caller_fn=llm_caller_fn)
        content_text = llm_res.get("text", "")
        extracted_files = self.extract_code_blocks(content_text)

        if not extracted_files:
            readme = (
                f"# Project Documentation\n\n"
                f"Generated by **SAGE Coding Agent (v6)** — *Build Big. Think Deep. Ship Fast.*\n\n"
                f"## 🚀 Overview\n{instruction}\n\n"
                f"## 📁 Project Architecture\n"
                f"- **Backend**: RESTful API server with SQLite persistence (`backend/`)\n"
                f"- **Frontend**: Modern responsive web application (`frontend/`)\n"
                f"- **DevOps**: Docker and compose containerization (`Dockerfile`, `docker-compose.yml`)\n"
                f"- **Tests**: Automated unit and integration test suites (`tests/`)\n\n"
                f"## 🛠️ Quick Start\n"
                f"### Local Setup\n"
                f"```bash\n"
                f"# 1. Install dependencies\n"
                f"pip install -r requirements.txt\n\n"
                f"# 2. Run backend server\n"
                f"python backend/server.py\n\n"
                f"# 3. Run automated tests\n"
                f"python -m unittest discover -s tests\n"
                f"```\n\n"
                f"### Docker Deployment\n"
                f"```bash\n"
                f"docker-compose up --build\n"
                f"```\n\n"
                f"## 📖 API Reference\n"
                f"| Method | Endpoint | Description |\n"
                f"|---|---|---|\n"
                f"| GET | `/api/health` | Service health status |\n"
                f"| GET | `/api/items` | List active items |\n"
            )
            extracted_files.append({"language": "markdown", "path": "README.md", "content": readme})

        return {
            "success": True,
            "role": self.role,
            "agent_name": self.name,
            "summary": content_text or "README and developer documentation generated.",
            "generated_files": extracted_files
        }
